services:
  api:
    image: "node:20.12"
    container_name: "api"
    command: /bin/bash -c "yarn install && yarn run start"
    working_dir: "/usr/app"
    volumes: 
      - "$PWD:/usr/app"
    ports:
      - "8080:8000"
    networks:
      - redis-postgres


networks:
  redis-postgres:
    driver: bridge
    name: redis-postgres

